### ISSUE TITLE
Add LL logo and branding

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-termsandconditions#3]
<img width="779" alt="Screen Shot 2023-09-01 at 10 37 02 AM" src="https://github.com/LemmaLegalConsulting/docassemble-termsandconditions/assets/65858862/3cf9174f-e087-4eeb-b829-cf7339c7ba21">

**Comment by miabonardi** [comment]
@stavros-0 I added the logo. Could you use these colors in the bootstrap:

#4422ee (dark purple)
#7988e6 (light purple)
#8daaf9 (light blue)

text should be black, gray can be used for other things
<img width="1289" alt="Screen Shot 2023-09-10 at 5 38 24 PM" src="https://github.com/LemmaLegalConsulting/docassemble-termsandconditions/assets/65858862/ff5aaddc-ab50-4920-987c-4bfe0588c1af">

**Comment by stavros-0** [comment]
yes
