### ISSUE TITLE
Add questions for undefined variables

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-termsandconditions#6]
Turn `skip undefined` in the attachments block to `False` and you will find there are numerous variables that are undefined and need questions added, including: 

website_free_to_use 
include_other_info 
sources (object)
use_google_services 
text_and_email 
choices (object)
organizations[0].email

**Comment by stavros-0** [comment]
I was able to add sources and choices, but I wasn't sure if there should be a dropdown with a list of options for choices and then other_choice would be an option that the user picks if they do not see an option in the dropdown list.

<img width="687" alt="Screenshot 2023-09-02 at 2 11 19 PM" src="https://github.com/LemmaLegalConsulting/docassemble-termsandconditions/assets/123116833/16ec1272-7070-4655-9f62-7af109fe05d2">

**Comment by miabonardi** [comment]
Here is the choices list: 

256 bit encryption
Software firewalls
Limited access controls
Continual monitoring
Regular security updates

other_choice should be an option and other_choice_description should be what user types in to describe the other choice.
